language: node_js
node_js:
- '6.1'
notifications:
  slack:
    secure: Y8TlA/voHgrLlCMUc7HlJQBeYameNHySC8+x5KHF2xPO3VzJtz9VHqARgsZRhggKrLngVxzWJ/iPwZAbFYoGkme9KQQ0NgkCmSG2rms1rLtiy8yhwb0mNBcvM/+UehaTw8Bq8ZwaYlFtjS0NDHr1OVT4VGO4yilqhFf6fKSuv2eRU3UY7t6uEFYE5L2CO6zZtU+zHPu3OTHtCMFEeL1NKDTy3caMCdhPCeGnXz0FGgJ9xi6F7diScIol/h0cjiWZhoJk+fiEDfuNMD5q7xa1eGGYBZYODJB66S7Nk6zrdxi8FBuulyYX6E1gH9bRFCE6vXbIY33/vbFEi+r1NFqkc6hhNiE7aV4C5E6GQlqetVU8xae+VFHau/kUTJLgTEswwEmq1Ha3pc7RMOCSivkc2PyM6YG97tn4/DquzRbE8s8+muevsatmBOFXtHUTy8tQdUlD/tAYj2kMvi3AagUWaU+EyimxrcWRRhDls0HdJqfBiRRSbsCreJk4yLftRn2m2XavzdJtfAHeHZse2fnDJf8Q0zQM7iO8/gP8yxvxuJpsopv5eQ3lFQAWjTEiY03YtQCLcf9dQR2Gx9LHOYeKAhMSw+ZspnnGYi/YFbX4YPeaRaGtipKHVnbvayvb8CruWmNTbA9G2oxD5mSfGbZjr0CI9PPGdG9Ydwpr77x1ydM=
